assetic:
    debug: false
    bundles: []
    use_controller:
        enabled: true
        profiler: true
    filters:
        cssrewrite: ~
        scss:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
            apply_to: '\.(scss|sass)$'
        lessphp:
            apply_to: '\.less$'
        jsqueeze:
            apply_to: '\.js$'