twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        navbar:
            - { path: 'dashboard', title: 'Dashboard'}
            - { path: 'month', title: 'Months'}
            - { path: 'app_logout', title: 'Logout'}